# Generated by Django 5.0.6 on 2024-07-18 06:38

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=25, prefix='', unique=True)),
                ('Name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(default='Clothes', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(default='No description')),
                ('size', models.CharField(default='N/A', max_length=12)),
                ('not_available', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('stock', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Rating', models.CharField(choices=[('⭐✰✰✰✰', '1'), ('⭐⭐✰✰✰', '2'), ('⭐⭐⭐✰✰', '3'), ('⭐⭐⭐⭐✰', '4'), ('⭐⭐⭐⭐⭐', '5')], default='⭐⭐⭐✰✰', max_length=20)),
                ('Discounted_Sales', models.BooleanField(default=False)),
                ('Discounted_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('New_Arrival', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default='Category not available', on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
