# Generated by Django 5.0.6 on 2024-07-18 06:41

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=25, prefix='catID', unique=True),
        ),
    ]
