# Generated by Django 4.1.13 on 2024-07-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_image_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discounted_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='Discounted_Sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='New_Arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.CharField(choices=[('1', '⭐✰✰✰✰'), ('2', '⭐⭐✰✰✰'), ('3', '⭐⭐⭐✰✰'), ('4', '⭐⭐⭐⭐✰'), ('5', '⭐⭐⭐⭐⭐')], default='⭐⭐⭐✰✰', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='N/A', max_length=12),
        ),
    ]
