# Generated by Django 4.1.13 on 2024-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cart_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_Id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
