# Generated by Django 5.0.6 on 2024-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_image_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Town',
            field=models.CharField(default='', max_length=20),
        ),
    ]
