# Generated by Django 5.0.6 on 2024-10-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_city_user_profile_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(upload_to='Profile_PICS'),
        ),
    ]
